### ISSUE TITLE
About generate ER diagrams

### ISSUE THREAD

**Issue by micalevisk** [eugene-manuilov/typeorm-uml#10]
Do you think that we can use this tool to generate [entity relationship diagrams](https://plantuml.com/ie-diagram) as well? :eyes:

**Comment by eugene-manuilov** [comment]
Hi @micalevisk 

I have just published a new version of the `typeorm-uml` (1.3.0) that makes use entity relationship diagrams. Could you please install it on your end and let me know if it's what you need?

**Comment by micalevisk** [comment]
it works! This is exactly what I'm looking for :+1: thanks.
