### ISSUE TITLE
Marks foreign keys

### ISSUE THREAD

**Issue by micalevisk** [eugene-manuilov/typeorm-uml#17]
I think it would be nice to have the suffix `<<FK>>` to all foreign keys columns

https://github.com/eugene-manuilov/typeorm-uml/blob/2eaa70000978202e615b1baf01ad8563fe5a667d/src/UmlBuilder.ts#L131

You can verify if the column is foreign key by using `if (!!column.referencedColumn)` ([source](https://github.com/typeorm/typeorm/blob/6ce65fbf6be5e696c3ae907d3f8e63b1e7332a1e/src/metadata/ColumnMetadata.ts#L263-L267))

What do you think?

**Comment by eugene-manuilov** [comment]
Yes, I like it. Added to the `develop` branch (#21). Will ship it with the next release.

**Comment by eugene-manuilov** [comment]
The new version `1.4.0` has been published and this feature has been shipped. Thanks, @micalevisk! :tada:
