### ISSUE TITLE
Support changing arrows direction

### ISSUE THREAD

**Issue by micalevisk** [eugene-manuilov/typeorm-uml#18]
What about add the `--direction` option to allow us specify a connection direction?

```
  --direction                    [default: TB] Arrows directions. TB=top to bottom, LR=left to right.
```

basically append the string `'left to right direction\n'` or `'top to bottom direction\n'` after `'@startuml\n'`
https://github.com/eugene-manuilov/typeorm-uml/blob/2eaa70000978202e615b1baf01ad8563fe5a667d/src/UmlBuilder.ts#L25-L27

**Comment by eugene-manuilov** [comment]
Yep, good idea too. Thanks! Added it to the `develop` branch (#21) and will ship it with the next release.

**Comment by eugene-manuilov** [comment]
Ok, the new version `1.4.0` has been published and this feature has been shipped. Thanks, @micalevisk! :tada:
