### ISSUE TITLE
Change the `--direction` short option name

### ISSUE THREAD

**Issue by micalevisk** [eugene-manuilov/typeorm-uml#23]
Since _**d**ownload_ and _**d**irection_ options have the same short option (`-d`), I think you should rename the latest added one to disambiguate this. What about `-D`?

**Comment by eugene-manuilov** [comment]
Good catch, @micalevisk! Thanks! I have updated it to be `-D`. It will be shipped with the next version.

**Comment by eugene-manuilov** [comment]
Just released the new version 1.5.0 which contains this fix. @micalevisk do you mind to check it on your end?

**Comment by micalevisk** [comment]
it works! ty
