### ISSUE TITLE
Customize colors

### ISSUE THREAD

**Issue by raphael-leger** [eugene-manuilov/typeorm-uml#27]
Hi,

Currently the colors of the diagram are hardcoded, for instance:
https://github.com/eugene-manuilov/typeorm-uml/blob/6bab2db1a82f358f6816ff297ca4b6141a78be3a/src/builder/uml-builder.class.ts#L43-L45

It would be nice to have a set of flags enabling their customization such as:

```
--primary-key-color #aaaaaa 
--foreign-key-color #aaaaaa
--column-color #aaaaaa
--entity-background-color #aaaaaa
--entity-border-color #aaaaaa
--arrow-color #aaaaaa
```

**Comment by eugene-manuilov** [comment]
Hi @raphael-leger!

Thanks, for the suggestion. I have implemented it and published as the `@next` version for now (use `npm i -D typeorm-uml@next` to install it). Could you please check it on your end and let me know if it is what you need?

You should be able to define colors using `--color <key>=<value>` flags where `<key>` can be `pkey`, `fkey`, `column`, `class.BackgroundColor`, `class.BorderColor` and `class.ArrowColor`. For example:

```sh-session
typeorm-uml path/to/ormconfig.json --color pkey=#00ff00 --color fkey=#00aa00 --color column=#007700
```

**Comment by raphael-leger** [comment]
Thanks for the quick implementation, it appears to be working well 👍

**Comment by eugene-manuilov** [comment]
Awesome! Closing this ticket then. This will be shipped with the next release. For now, it can be installed using `@next` tag.
