### ISSUE TITLE
Customize plantuml server url

### ISSUE THREAD

**Issue by raphael-leger** [eugene-manuilov/typeorm-uml#28]
Hi,

Currently the plantuml server url is hardcoded, meaning we can only use the official plantuml server to generate diagrams:
https://github.com/eugene-manuilov/typeorm-uml/blob/53d5b0eff662a2e776746a710eb07d2f4a00d6ce/src/builder/typeorm-uml.class.ts#L96

From a security point-of-view, sending a whole database structure to an external server so that it generates a diagram is not a good practice.

There are ways of hosting a plantuml server (eg. using [this docker image](https://hub.docker.com/r/plantuml/plantuml-server))

Once hosted, it can be made available on any custom url - may it be accessible on the world wide web or just within an internal infrastructure.

In order for such a custom server to be supported by this library, it would be nice to be able to specify the plantuml server url as an optional flag.

`--plantuml-url: string` (default: `http://www.plantuml.com/plantuml`)

Feel free to take the pull request into consideration

**Comment by eugene-manuilov** [comment]
Awesome! Thanks a lot, @raphael-leger!

**Comment by eugene-manuilov** [comment]
Ok, published it as `1.6.0-1` via `@next` tag for testing.
