### ISSUE TITLE
OneToOne relation with wrong UML arrows

### ISSUE THREAD

**Issue by hugoseabra** [eugene-manuilov/typeorm-uml#31]
Good job on the project @eugene-manuilov .

I appreciate you check `OneToOne` relations. The arrows in diagram behave like `ManyToOne` relation.

Example:

```typescript
 @OneToOne(() => StandardName, {
    eager: true,
    onDelete: "SET NULL"
  })
  @JoinColumn()
  standardName!: StandardName;
``` 

In UML I have:

![image](https://user-images.githubusercontent.com/166136/102257305-550bb780-3eeb-11eb-9386-648ff40e1d0b.png)

Actually the arrows should be `-|---------`

**Comment by eugene-manuilov** [comment]
Thanks for submitting it, @hugoseabra! I have fixed it and published the new version `1.6.1`. Could you please update it on your end and try it out? Let me know if it works correctly now.

**Comment by eugene-manuilov** [comment]
Ok, I think this can be considered as resolved. Closing this ticket. Feel free to open a new one if something doesn't work.

**Comment by hugoseabra** [comment]
Yes, correctoin applied in `1.6.1`.

Thanks @eugene-manuilov !!!
