### ISSUE TITLE
Postgres' "timestamptz" should be recognized as "TIMESTAMP WITH TIMEZONE"

### ISSUE THREAD

**Issue by leonidasv** [eugene-manuilov/typeorm-uml#32]
Fields using `timestamptz` are being translated to `TIMESTAMP WITHOUT TIMEZONE`. However, `timestamptz` is an abbreviation for `TIMESTAMP WITH TIMEZONE`: https://www.postgresql.org/docs/current/datatype-datetime.html

![chrome_HXUbIsmkww](https://user-images.githubusercontent.com/17609157/104644966-3dac1f80-568d-11eb-89d2-c85e76d44e52.png)

**Comment by eugene-manuilov** [comment]
Hm... that's weird because columns types are translated by the typeorm itself... @leonidasv, can you show me your typeorm config and the `Wallet` entity?

**Comment by leonidasv** [comment]
@eugene-manuilov My fault, those fields weren't using `"timestamptz"`, but `"timestamp"`. Changing them to actually use `timestamp with timezone` made everything work as intended.
