### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by markush97** [eugene-manuilov/typeorm-uml#36]
```bash

[redacted]\node_modules\.bin\typeorm-uml:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at main ([redacted]\node_modules\ts-node\src\bin.ts:198:14)
    at Object.<anonymous> ([redacted]\node_modules\ts-node\src\bin.ts:288:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

```

what is going on here? is this my fault? could not figure it out...

**Comment by eugene-manuilov** [comment]
Hi @markush97 

hard to say without context. What do you try to do and which command have you run? Can you give more details? Or you have already figured it out?

**Comment by gauravpan** [comment]
I am having same error 
  cmd : `ts-node ./node_modules/.bin/typeorm-uml ormconfig.json`
ormconfig.json : 

```  json
{
   "type": "mysql",
   "host": "localhost",
   "port": 6603,
   "username": "root",
   "password": "root",
   "database": "food",
   "entities": [ "src/db/entity/**/*.ts"]
}

```

**Comment by talfreds** [comment]
I'm having this issue as well. 

```ts-node ./node_modules/.bin/typeorm-uml src/ormconfig.ts```

Windows 10
Node: v14.15.4

Seems to be this issue: https://github.com/typeorm/typeorm/issues/317 and not directly related to typeorm-uml ?

The solution provided works for typeorm migrations but I don't see an equivalent file in typeorm-uml to use as an alternative.

**Comment by gustavoacs99** [comment]
Same thing here.

`ts-node ./node_modules/.bin/typeorm-uml ormconfig.json`

Windows 10
Node: v14.17.0

Would it be possible to provide a `cli.js` file to be used in windows as mentioned  [here](https://github.com/typeorm/typeorm/issues/317) and pointed by @talfreds ?

**Comment by PolaMalak** [comment]
for anyone still facing this error try to change your db:diagram script to 
`ts-node ./node_modules/typeorm-uml/bin/run ormconfig.json`

**Comment by talfreds** [comment]
> for anyone still facing this error try to change your db:diagram script to `ts-node ./node_modules/typeorm-uml/bin/run ormconfig.json`

Thanks for the suggestion, but I get

`Error: Cannot find module '{obscured}\node_modules\typeorm\connection\ConnectionMetadataBuilder'`

**Comment by PolaMalak** [comment]
> `Error: Cannot find module '{obscured}\node_modules\typeorm\connection\ConnectionMetadataBuilder'`

ConnectionMetadataBuilder is used in uml-builder.class.js in typeorm-uml/builder
 try to check that the import/require reads the valid typeorm path

**Comment by pipehnz** [comment]
Hello there,  I have the same issue I have been trying to define the scripts suggested here, in my case:

`ts-node ./node_modules/typeorm-uml/bin/run ormconfig.json` 

Output:

`throw new Error('No entities have been found. Please, check your typeorm config to make sure you have configured it correctly.');`

Any solution?

**Comment by PolaMalak** [comment]
> `throw new Error('No entities have been found. Please, check your typeorm config to make sure you have configured it correctly.');`

whether you don't have any entites or your ormconfig.json entites property is wrong, write the valid location of your entites for ex. 
```
"entites" : [
     "src/entites/*.ts"
]
```

**Comment by eugene-manuilov** [comment]
The new version `1.6.5` is published. Please, let me know if it helps with this issue.

**Comment by pipehnz** [comment]
Thank you @PolaMalak @eugene-manuilov with the version `1.6.5` works. 💯

**Comment by talfreds** [comment]
Works for me as well, thanks @eugene-manuilov !

I used ormconfig.json, I'm assuming there isn't support for `.ts` config files

**Comment by eugene-manuilov** [comment]
Awesome! Thanks, everyone!

**Comment by eugene-manuilov** [comment]
> I used ormconfig.json, I'm assuming there isn't support for `.ts` config files

@talfreds try to run the following:

```
ts-node ./node_modules/.bin/typeorm-uml ormconfig.ts
```

Not sure whether it helps though.

**Comment by pipehnz** [comment]
`{
    "scripts": {
        "typeorm:diagram": "ts-node ./node_modules/typeorm-uml/bin/run ormconfig.json"
    }
}`

that's works for me, can you try? @talfreds @eugene-manuilov

**Comment by talfreds** [comment]
> `{ "scripts": { "typeorm:diagram": "ts-node ./node_modules/typeorm-uml/bin/run ormconfig.json" } }`
> 
> that's works for me, can you try? @talfreds @eugene-manuilov

That works for me, but the ormconfig.ts file used in my project doesn't (I created the json config specifically for typeorm-uml).

> > I used ormconfig.json, I'm assuming there isn't support for `.ts` config files
> 
> @talfreds try to run the following:
> 
> ```
> ts-node ./node_modules/.bin/typeorm-uml ormconfig.ts
> ```
> 
> Not sure whether it helps though.

Thanks but no luck :( I still get the original error with the .bin, and I get a "No entities have been found. Please, check your typeorm config to make sure you have configured it correctly." error.

It doesn't seem to get the `export default` config
