### ISSUE TITLE
Add format puml to generate PlantUML diagram

### ISSUE THREAD

**Issue by prokopsimek** [eugene-manuilov/typeorm-uml#5]
The txt format generates diagram "as image" and it would be great to generate the PlantUML diagram directly in `.puml` format.

**Comment by eugene-manuilov** [comment]
Hey @prokopsimek.

Thanks for submitting your request. I have just released a new version (1.2.0) that has a new format - `puml`. If you use it, it will display a UML diagram source code instead of a URL link. Does it work for you?

**Comment by prokopsimek** [comment]
@eugene-manuilov Thanks for the implementation! It's not possible to download a diagram in `puml` format so I have just created a PR solving this issue: https://github.com/eugene-manuilov/typeorm-uml/pull/7

**Comment by eugene-manuilov** [comment]
Thanks @prokopsimek! Merged and published 1.2.1. :tada:

**Comment by eugene-manuilov** [comment]
Closing this ticket. Feel free to open a new one if needed.
