### ISSUE TITLE
Not able to install, typeorm-uml speacially

### ISSUE THREAD

**Issue by rushike** [eugene-manuilov/typeorm-uml#9]
I read about typeorm on  some stackoverflow post. 

I don't know why I am not able to install the _package_ from npm. At same time I can install other packages with ease

Here is sinppet, I am using windows 10.

```
F:\rushikesh\website\maths163>npm install -D typeorm-uml
npm ERR! Unexpected end of JSON input while parsing near '...s://registry.npmjs.or'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rushi\AppData\Roaming\npm-cache\_logs\2020-07-17T05_10_27_174Z-debug.log
```

Here is another command I tried
```
F:\rushikesh\website\maths163>npm install  typeorm-uml
npm ERR! Unexpected end of JSON input while parsing near '...s://registry.npmjs.or'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rushi\AppData\Roaming\npm-cache\_logs\2020-07-17T05_10_41_177Z-debug.log```

**Comment by eugene-manuilov** [comment]
Hi @rushike 

sorry for late reply, but have you managed to install it or you still have issues with it?

**Comment by eugene-manuilov** [comment]
Ok, going to close this issue. Feel free to create a new one if you still have problems.
